//let edad = prompt('ingrese su edad: ')

//console.log(Number(edad))
//console.log(parseInt(edad))
//let comprobarEdad = Number(edad)>18
//console.log(comprobarEdad)

let comprobacion1 = 5 < 1.9
let comprobacion2 = 10 === 10

//operadores 
let resultado = comprobacion1 && comprobacion2 && true
let resultado2 = comprobacion1 || comprobacion2 || false

console.log(resultado2)

let resultado3 = !(comprobacion1 && comprobacion2 && true)
console.log(resultado3)

let booleano= true
console.log(booleano)
console.log(!booleano)
